---
- name: Installation database
  hosts: database
  remote_user: bob
  vars:
    user: volibear
  roles:
    - utils
    - user
    - database


- name: Installation
  hosts: web
  remote_user: bob
  vars:
    user: volibear
  roles:
    - utils
    - user
 #   - web
