---
 - name: Installation db
   mysql_db:
     name: "{{ mysql_db }}"
   become: yes

#   apt: name=mysql_db state=latest
 - name: Create user
   become: yes 
   mysql_user: 
     name: "{{ mysql_user }}"
     password: "{{ mysql_password }}"
     priv: "*.*:ALL"
   
